# Generated by Django 5.0.3 on 2024-03-12 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pupils',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=255)),
                ('profile_image', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'pupil',
                'db_table': 'pupils',
            },
        ),
    ]
