# Generated by Django 5.0.3 on 2024-03-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pupils', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pupils',
            name='mark1',
            field=models.IntegerField(default=1, verbose_name='mark1'),
        ),
        migrations.AddField(
            model_name='pupils',
            name='mark2',
            field=models.IntegerField(default=1, verbose_name='mark2'),
        ),
        migrations.AddField(
            model_name='pupils',
            name='mark3',
            field=models.IntegerField(default=1, verbose_name='mark3'),
        ),
        migrations.AddField(
            model_name='pupils',
            name='mark4',
            field=models.IntegerField(default=1, verbose_name='mark4'),
        ),
        migrations.AddField(
            model_name='pupils',
            name='mark5',
            field=models.IntegerField(default=1, verbose_name='mark5'),
        ),
        migrations.AddField(
            model_name='pupils',
            name='mark6',
            field=models.IntegerField(default=1, verbose_name='mark6'),
        ),
        migrations.AlterField(
            model_name='pupils',
            name='fullname',
            field=models.CharField(max_length=255, verbose_name='fullname'),
        ),
        migrations.AlterField(
            model_name='pupils',
            name='profile_image',
            field=models.CharField(max_length=255, verbose_name='profile_image'),
        ),
    ]
